apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-judge-deployment
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: code-judge
  template:
    metadata:
      labels:
        app: code-judge
    spec:
      containers:
        - name: code-judge
          image: tarunclub/code-judge-app:1.0
          resources:
            limits:
              cpu: '0.5' # Adjust resource limits as needed
              memory: '512Mi'
          env:
            # Define any environment variables your application needs
          ports:
            # If your application exposes a port, specify it here
      restartPolicy: Always # Use "Always" for long-running processes like jobs
