apiVersion: v1
kind: Service
metadata:
  name: code-judge-service
spec:
  selector:
    app: code-judge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Replace with the actual port your application listens on
  type: ClusterIP # Use "LoadBalancer" or "NodePort" for external access if needed
